language: python
python: 2.7
sudo: false
cache:
  directories:
  - ../build/plonetheme.mytheme/eggs
install:
- nvm install 8
- pip install mr.bob
- sed -ie "s#5-latest#$PLONE#" .travis.ini
- mrbob -O ../build -c .travis.ini .
script:
- make -C ../build/plonetheme.mytheme info build
env:
- PLONE=5.0.8
- PLONE=5.1.5
- PLONE=5.2.0
- PLONE=5.2.1
