language: python
python: 2.7
sudo: false
cache:
  directories:
  - ../build/plonetheme.mytheme/eggs
install:
- nvm install 6
- pip install mr.bob
- sed -ie "s#5-latest#$PLONE#" .travis.ini
- if [ "$SVG" ]; then sed -ie "s#svg = no#svg = $SVG#" .travis.ini; fi
- mrbob -O ../build -c .travis.ini .
script:
- make -C ../build/plonetheme.mytheme info build
env:
- PLONE=5.0.5
- PLONE=5.0.6
- PLONE=5.0.7
- PLONE=5.0.8
- PLONE=5.0-latest
- PLONE=5.0-latest SVG=yes
- PLONE=5.1
# PLONE=5.1.1 # is missing some TinyMCE resources
- PLONE=5.1.2
- PLONE=5.1.2 SVG=yes
